name: pr-preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        if: github.event.action != 'closed'
        with:
          python-version: 3.x

      - name: Build site
        if: github.event.action != 'closed'
        run: |
          pip install mkdocs-material mkdocs-callouts
          mkdocs build --site-dir _site

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site
